### ISSUE TITLE
Make violent crime categorizer

### ISSUE THREAD

**Issue by brancengregory** [openjusticeok/ojodb#34]

**Comment by brancengregory** [comment]
Is this implemented in the db or do we need a helper function?

**Comment by rcgentzler** [comment]
We'll need a helper function. Violent/non-violent has a few different nuances in different contexts, so we'll need to be very thoughtful about defining them.

**Comment by brancengregory** [comment]
This will be handled by https://github.com/openjusticeok/ojoregex
